import {
  Activity,
  AlertTriangle,
  Bot,
  Box,
  Brain,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsDownUp,
  ChevronUp,
  Circle,
  CircleDot,
  Clock,
  Command,
  Copy,
  Download,
  FileText,
  Flame,
  Folder,
  FolderOpen,
  GitBranch,
  GitCommitHorizontal,
  HelpCircle,
  Info,
  KeyRound,
  Layers,
  LayoutGrid,
  ListChecks,
  Loader2,
  type LucideProps,
  MessageSquare,
  Minus,
  MoreHorizontal,
  Package,
  Palette,
  PanelBottom,
  Pencil,
  Plug,
  Plus,
  RefreshCw,
  Rocket,
  Search,
  Server,
  Settings,
  ShieldCheck,
  Sparkles,
  Square,
  SquarePen,
  Target,
  Terminal,
  Timer,
  Trash2,
  Unlock,
  Wrench,
  X,
  Zap,
} from 'lucide-vue-next';
import type { FunctionalComponent } from 'vue';

export type LucideIcon = FunctionalComponent<LucideProps>;

/**
 * Named icon registry for config-driven UI (nav items, commands, permissions).
 * Prefer importing Lucide icons directly when the icon is static in a template.
 */
export const ICONS = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  brain: Brain,
  bot: Bot,
  box: Box,
  check: Check,
  'check-circle': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-down-up': ChevronsDownUp,
  circle: Circle,
  'circle-dot': CircleDot,
  clock: Clock,
  command: Command,
  copy: Copy,
  download: Download,
  file: FileText,
  flame: Flame,
  folder: Folder,
  'folder-open': FolderOpen,
  'git-branch': GitBranch,
  'git-commit': GitCommitHorizontal,
  help: HelpCircle,
  info: Info,
  key: KeyRound,
  layers: Layers,
  'layout-grid': LayoutGrid,
  'list-checks': ListChecks,
  loader: Loader2,
  message: MessageSquare,
  minus: Minus,
  more: MoreHorizontal,
  package: Package,
  palette: Palette,
  'panel-bottom': PanelBottom,
  pencil: Pencil,
  plug: Plug,
  plus: Plus,
  refresh: RefreshCw,
  rocket: Rocket,
  search: Search,
  server: Server,
  settings: Settings,
  'shield-check': ShieldCheck,
  sparkles: Sparkles,
  square: Square,
  'square-pen': SquarePen,
  target: Target,
  terminal: Terminal,
  timer: Timer,
  trash: Trash2,
  unlock: Unlock,
  wrench: Wrench,
  x: X,
  zap: Zap,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function resolveIcon(name: string): LucideIcon | null {
  if (name in ICONS) {
    return ICONS[name as IconName];
  }
  return null;
}
